### ISSUE TITLE
왜 아무것도 없어요?!

### ISSUE THREAD

**Issue by 614project** [dply-app/DPLY.APP-INTO#3]
아잇 싯팔, 아무것도 없으면 이거 왜올린거야! 이슈맛좀 볼레?

**Comment by Mireu-Labcon** [comment]
아직 완벽하게 개발된게 아니라서 그렇게 됨

**Comment by 614project** [comment]
> 아직 완벽하게 개발된게 아니라서 그렇게 됨

어쩌라고(?)

**Comment by kms0219kms** [comment]
아 고객님~~ 저희 서비스는 다른 고객님들께 불편한부분을 해소하기위한 목적으로 블랙리스트을 지원하고 있습니다 ^^
