### ISSUE TITLE
아직도?

### ISSUE THREAD

**Issue by 614project** [dply-app/DPLY.APP-INTO#4]
아잇 싯팔 아짓도 여기 바뀐게 하나도 없잖아 지금 8월이야 8월 뺴애애애애액, 이럴꺼면 왜열었어 빼애액, dply 한강 갔음?

**Comment by Mireu-Labcon** [comment]
뭐... 만들고 있다만 어떻게 하라고 그러면 블랙리스트에서 너 포함하겠음 ^^

**Comment by 614project** [comment]
씁, 그건 좀...

**Comment by Mireu-Labcon** [comment]
아 고객님~~ 저희 서비스는 다른 고객님들께 불편한부분을 해소하기위한 목적으로 블랙리스트을 지원하고 있습니다 ^^
