### ISSUE TITLE
해명해(?)

### ISSUE THREAD

**Issue by 614project** [dply-app/DPLY.APP-INTO#5]
0. 잘되나가요?

1. 인터넷 속도는 한국인이 좋아하는 속도인가요?

2. 서버는 시원한가요? (스로틀링 덜하나요?)

3. dply 가지고 또 다른 호스팅 서비스 마련 가능한가요?
(예: dply 서버를 이용한 웹호스팅 서비스, 상업적)

4. exe가 실행이 가능한가요?
(.Net 포함)

5. 스토리지에 올린 파일은 모두 암호화 되나요?
(쉽게 말하면 내가 올린게 남은 볼수가 없는가?)

6. 서버는 무엇으로 조작하나요? 
(예: 프로그램, 웹사이트, 타사 프로그램)

7. 공유섭, VM섭, 독립섭에서 무엇을 하기 좋은지 추천해주세요.
(마인크래프트 제외)

8. 공유섭, VM섭, 독립섭에서 공인 ip를 사용할수 있나요?

9. cpu와 ram만 알려주셨는데, gpu는 없나요? gpu 사양을 알려주세요.

10. 리눅스의 경우 sudo를 사용할수 있나요?
(있다면 sudo rm -rf /* 를 하면 어떻게 되나요?)

**Comment by Mireu-Labcon** [comment]
0. 잘은 모르겠습니다
1. 인터넷 속도는 무난합니다
2. 서버는 조금 시원합니다
3. 상업적으로 사용이 가능합니다
4. 도커 컨테이너는 전부다 리눅스러 되어있기에 exe 프로그램은 작동하지않습니다
5. 모두 암호화됩니다
6. 서버 조작은 서비스 보안상으로 알려드리지 않음을 안내합니다
7. 현제 기획상으로는 해당 서비스을 하는게 목표이지만 서비스의 안정성을 위해서 현제 공유 서버만 할수있게 되었습니다
8. 공인 ip는 사용 불가합니다.
9. GPU는 서비스 안정성이 확보되는경우 진행 할려고 합니다
10. 컨테이너 상으로는 가능은 합니다

**Comment by 614project** [comment]
0. 1년치로 결제가 가능한가요?

1. 나이에 제한이 없나요? (잼민이들)

2. 도커라니... 거기다가 리눅스... 학생이 사용하기에 쉬울지 의문인데요, 따로 뭐 사용법 제공하나요?

3. 암호화가 된다는데, 무슨 방식이 들어가나요?

4. dply 프로젝트에 참여할수 있나요(?)

5. 문상등으로 결제가 된다고 하시는데, 월 단위로 결제되는데, 만약 많이 미뤄질경우, 무슨 일이 발생하나요?

6. 이 서비스가 적어도 몇년 갈것으로 예상하나요?

**Comment by Mireu-Labcon** [comment]
0. 1년치로 결제 가능하게 준비중에있습니다
1. 나이에 제한은 없습니다
2. 사용법을 따로 제공을 하기 위해서 매뉴얼을 준비중입니다
3. 해쉬가 들어갑니다
4. 안될것 같습니다
5. 그건 기획이 되어있지 않아 안내 해들릴수없을것 같습니다
6. 최소 1개월 최대 1년밖에 안갈것 같습니다
